version: "2.1"
services:
  dvr:
    container_name: HDHomeRunDVR
    image: greg2dot0/hdhomerundvr:latest
    network_mode: host
    environment:
    - PUID=99
    - PGID=100
    - UMASK_SET=000 #optional
    - TZ=America/New_York
    volumes:
      - /Users/Greg/temp:/dvrdata
      - /Users/Greg/opt/appdata:/config
    restart: unless-stopped
